import React from 'react';
import { GetStaticProps } from 'next';
import Head from 'next/head';

import { getAllposts, getMultiplePosts } from '@/lib/notionAPI';
import { Post } from '@/domain/models/Post';
import SinglePost from '@/components/Post/SinglePost';

interface Props {
  posts: Post[];
}

interface Params {
  params: {
    page: string;
  };
}

export const getStaticPaths = async () => {
  const allPosts = await getAllposts();

  if (!allPosts) {
    console.error('cannot fetch blog posts');
    return;
  }
  const paths: Params[] = [...Array(Math.ceil(allPosts.length / 10))].map(
    (_, i) => {
      return { params: { page: (i + 1).toString(10) } };
    }
  );

  return {
    paths,
    fallback: 'blocking',
  };
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const DEFAULT_POSTS_COUNT = 5;
  const posts = (await getMultiplePosts(DEFAULT_POSTS_COUNT)) || [];

  return {
    props: {
      posts,
    },
    revalidate: 60 * 60 * 6,
  };
};

const Post = ({ posts }: Props) => {
  return (
    <>
      <div className="container w-full h-full mx-auto">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/fabicon.ico" />
        </Head>

        <main className="container w-full mt-16">
          <h1 className="text-5xl font-medium text-center mb-16">
            Notion Blog
          </h1>
          {posts.map((post) => (
            <SinglePost post={post} key={post.slug} />
          ))}
        </main>
      </div>
    </>
  );
};

export default Post;
