import Head from "next/head";
import { GetStaticProps } from "next";
import { Post } from "@/domain/models/Post";
import { getAllposts } from "@/lib/notionAPI";
import SinglePost from "@/components/Post/SinglePost";

interface Props {
  allPosts: Post[];
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const allPosts = await getAllposts() || [];

  return {
    props: {
      allPosts,
    },
    revalidate: 60 * 60 * 6,
  };
};

const Home = ({ allPosts }: Props) => {
  console.log("allPosts", allPosts);
  return (
    <div className="container w-full h-full mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fabicon.ico" />
      </Head>

      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">Notion Blog</h1>
        {allPosts.map((post) => (
          <SinglePost 
            post={ post }
            key={ post.slug }
          />
        ))}
      </main>
    </div>
  );
};

export default Home;
