import Head from 'next/head'
import { Post } from "@/domain/models/Post";
import { getAllposts } from '@/lib/notionAPI'
import { GetStaticProps } from 'next';

interface Props {
  allPosts: Post[];
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const allPosts = await getAllposts() || [];

  return {
    props: {
      allPosts,
    },
    revalidate: 60 * 60 * 6,
  };
};

const Home = ({ allPosts }: Props) => {
  console.log('allPosts', allPosts);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fabicon.ico" />
      </Head>
    </>
  )
}

export default Home;
